INSERT INTO users (name, phone, email)
VALUES
    ('김민서', '010-7926-7093', 'ligula.aliquam.erat@yahoo.org'),
    ('박서윤', '010-2442-8912', 'neque.morbi.quis@icloud.org'),
    ('이도윤', '010-1130-0377', 'egestas.lacinia.sed@icloud.com'),
    ('정하윤', '010-8895-8067', 'nam.porttitor.scelerisque@google.com'),
    ('한지우', '010-4814-5671', 'adipiscing@icloud.couk'),
    ('유건우', '010-3638-2552', 'velit.eget@yahoo.ca'),
    ('노예준', '010-6476-3161', 'sed.eu@aol.ca'),
    ('송하람', '010-6772-3319', 'neque.et@yahoo.com'),
    ('배도현', '010-0812-8874', 'dolor@hotmail.couk'),
    ('문시우', '010-2510-2557', 'enim@protonmail.couk'),
    ('오하린', '010-3764-8872', 'magna.lorem.ipsum@google.ca'),
    ('강서진', '010-1750-6233', 'eget.odio@hotmail.org'),
    ('권도영', '010-9268-4462', 'per.conubia@aol.com'),
    ('장민재', '010-1383-0467', 'lobortis.augue@icloud.couk'),
    ('백서율', '010-6827-4771', 'magna.sed@hotmail.com'),
    ('최예린', '010-4888-8246', 'pretium.neque@aol.org'),
    ('신지호', '010-5171-6830', 'per.conubia.nostra@hotmail.couk'),
    ('조민혁', '010-2971-6282', 'ac@icloud.net'),
    ('양하늘', '010-9441-8298', 'erat@icloud.net'),
    ('임도훈', '010-9761-1773', 'fringilla@aol.edu');


INSERT INTO posts (user_id, title, content)
VALUES
    (10, 'Docker 개념 정리', '컨테이너 기반 개발 환경을 구축하는 방법을 정리했어요.'),
    (3, 'Spring Boot 활용법', 'Spring Boot로 REST API를 만드는 법을 공유합니다.'),
    (15, 'Redis 캐시 활용', 'Redis를 활용한 캐싱 전략을 공유합니다.'),
    (8, 'AWS 배포 가이드', 'EC2와 S3를 활용한 배포 가이드를 작성해보았습니다.'),
    (1, '데이터베이스 설계 기초', '데이터베이스의 기초 개념을 정리해보았습니다.'),
    (7, '쿼리 최적화 기법', '인덱싱과 실행 계획을 활용한 성능 최적화 방법을 공유합니다.'),
    (12, 'JWT vs OAuth', '인증과 권한 부여 방식의 차이를 설명해봅니다.'),
    (5, 'Django REST Framework', 'DRF를 이용한 API 서버 구축 방법을 다뤄봤어요.'),
    (18, 'Apollo Client 활용법', 'React에서 GraphQL을 사용하는 방법'),
    (16, 'Git 명령어 정리', 'Git을 효과적으로 활용하기 위한 필수 명령어 정리'),
    (4, 'Next.js의 장점', 'SSR과 ISR을 활용하는 방법을 알아봅니다.'),
    (11, 'Stateful vs Stateless', 'Flutter에서 상태 관리를 다루는 방법'),
    (20, '메시지 큐 시스템', 'RabbitMQ와 Kafka의 차이를 비교해봅니다.'),
    (9, '알고리즘 문제 풀이', '오늘 풀어본 알고리즘 문제와 풀이 방법 공유!'),
    (14, 'Coroutine 활용하기', 'Kotlin에서 비동기 프로그래밍을 다루는 방법'),
    (6, 'Node.js 서버 구축', 'Express를 사용한 간단한 서버 구축 방법을 소개합니다.'),
    (13, 'MongoDB 사용법', 'NoSQL 데이터베이스인 MongoDB의 기본적인 CRUD 연산을 다뤄봤어요.'),
    (2, '비동기 처리 이해하기', 'async/await와 Promise를 활용하는 방법을 공유합니다.'),
    (19, 'Django 웹 개발', 'Django를 이용한 간단한 블로그 만들기 튜토리얼.'),
    (17, 'DevOps 도구 비교', 'Terraform, Ansible, Docker의 활용법'),
    (8, 'Lambda 활용하기', 'AWS Lambda를 이용한 서버리스 애플리케이션 구축'),
    (5, '파이썬 기본 문법', '파이썬을 처음 배우는 분들을 위한 기초 문법 정리.'),
    (9, 'DP 문제 해결법', '동적 계획법을 활용한 문제 해결 방법을 정리합니다.'),
    (3, 'JPA와 Hibernate', 'ORM을 활용한 데이터베이스 접근 방법을 소개합니다.'),
    (12, 'HTTP와 HTTPS 차이', '웹 보안의 기본 개념을 설명해봅니다.'),
    (4, 'React 상태 관리', 'Recoil과 Redux의 차이를 설명해봤어요.'),
    (15, '세션 스토리지와 캐시', '서버 상태 관리 방법 비교'),
    (7, 'MySQL vs PostgreSQL', '두 데이터베이스의 장단점을 비교해봤어요.'),
    (6, '웹소켓 실시간 채팅', 'Socket.io를 활용한 채팅 서버 개발 방법을 공유합니다.'),
    (18, 'GraphQL 소개', 'REST API와 GraphQL의 차이점을 비교했습니다.'),
    (1, 'SQL vs NoSQL', '두 가지 데이터베이스의 차이점을 분석해보았습니다.'),
    (11, 'Flutter로 앱 만들기', 'Flutter를 사용하여 간단한 To-Do List 앱을 만들어봤어요.'),
    (14, 'Kotlin 기본 문법', '안드로이드 개발을 위한 Kotlin 문법을 정리했습니다.'),
    (20, 'Kafka 기본 개념', 'Kafka의 기본 아키텍처와 활용 사례를 정리했어요.'),
    (2, '자바스크립트 ES6+', '화살표 함수와 let/const의 차이를 다뤄봤어요.'),
    (16, '브랜치 전략', 'Git Flow와 GitHub Flow의 차이를 설명합니다.'),
    (13, 'Aggregation Framework', 'MongoDB의 강력한 데이터 처리 도구를 활용하는 방법'),
    (17, 'CI/CD 개념', 'Jenkins와 GitHub Actions를 이용한 배포 자동화.');

